name: 'Build & Deploy'

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master
        with:
          python-version: '3.10'

      - name: python requirements
        run: pip install requirements.txt

      - name: dbt
        run: make run-dbt
        
      - name: evidence
        run: make evidence-build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: reports/build # The folder the action should deploy.
