name: 'Build & Deploy'

on:
  push:
    branches:
    - master
permissions:
  contents: write
jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master
        with:
          python-version: '3.10'

      - name: python requirements
        run: pip install -r requirements.txt

      - name: dbt
        run: |
          python starter/template_engine.py
          dbt run
        
      - name: evidence
        run: make evidence-run

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=reports/build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
