name: 'Build & Deploy'

on:
  push:
    branches:
    - master
permissions:
  contents: write
jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@master
        with:
          python-version: '3.10'

      - name: python requirements
        run: pip install -r requirements.txt

      - name: dbt
        run: |
          python starter/template_engine.py
          dbt run
        
      - name: evidence
        run: make evidence-run

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: reports/build # The folder the action should deploy.
